
home:
    path: /
    controller: App\Controller\HomeController::home

app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout