home:
    path: /
    controller: App\Controller\HomeController::home

app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    
app_user_index:
    path: /users
    controller: App\Controller\UserController::index


admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

admin_posts:
    path: /admin/post
    controller: App\Controller\Admin\PostController::post

comments_crud:
    path: /comment
    controller: App\Controller\Admin\CommentCrudController::index


users_crud:
    path: /users
    controller: App\Controller\Admin\UserCrudController::index
app_actus:
    path: /actus
    controller: App\Controller\AffichagePostController::index
    methods: GET

a_propos_de_nous:
  path: /a-propos-de-nous
  controller: App\Controller\AboutController::aboutUs

contact:
  path: /contact
  controller: App\Controller\ContactController::contact

post_search:
    path: /search
    controller: App\Controller\Admin\PostCrudController::home
    methods: GET


