
home:
    path: /
    controller: App\Controller\HomeController::home

app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

admin_posts:
    path: /admin/post
    controller: App\Controller\Admin\PostController::post